name: check

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

env:
  GO_VERSIONS: '["1.25", "1.26"]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go_versions: ${{ steps.go_versions.outputs.go_versions }}
    steps:
      - id: go_versions
        run: echo 'go_versions=["1.25", "1.26"]' >> "$GITHUB_OUTPUT"

  lint:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        go: ${{ fromJSON(needs.setup.outputs.go_versions) }}
    name: "golangci-lint / go@${{ matrix.go }}"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '${{ matrix.go }}'
      - uses: golangci/golangci-lint-action@v9
        with:
          version: 'v2.11.4'
  unit-test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        go: ${{ fromJSON(needs.setup.outputs.go_versions) }}
    name: "unit tests / go@${{ matrix.go }}"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '${{ matrix.go }}'
      - run: go test -v ./...
  release-test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        go: ${{ fromJSON(needs.setup.outputs.go_versions) }}
    name: "release test / go@${{ matrix.go }}"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version: '${{ matrix.go }}'
      - uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> 2'
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check the linux build version
        run: ./dist/etc-hosts-proxy_linux_amd64_v1/etc-hosts-proxy --version
