name: CI

on:
  push:
    tags:
      - v*.*.*
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

env:
  go_version: '1.26'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "${{ env.go_version }}"
          cache: false
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: "v2.12.0"

  tests:
    runs-on: ubuntu-latest
    name: acceptance tests
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "${{ env.go_version }}"
          cache: false
      - run: go test -v ./...

  suite:
    needs:
      - lint
      - tests
    runs-on: ubuntu-latest
    name: test suite
    steps:
      - run: echo Test suite completed

  release:
    permissions:
      contents: write # To update the release assets
      packages: write
    runs-on: ubuntu-latest
    needs:
      - suite
    name: release${{ !startsWith(github.ref, 'refs/tags/v') && ' test' || '' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "${{ env.go_version }}"
          cache: false
      - name: Set up Docker Buildx with docker-container driver
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Registry Login
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> 2"
          args: release --clean${{ !startsWith(github.ref, 'refs/tags/v')  && ' --snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check the linux build version
        run: ./dist/etc-hosts-proxy_linux_amd64_v1/etc-hosts-proxy --version
